/**
 * Nimbalyst control plane HTTP routes for external automation.
 *
 * Exposes a narrow programmatic API at /control/v1/* on the existing
 * internal MCP HTTP server (httpServer.ts). Designed so external agents
 * (Claude Code, regression test harnesses, the nimbalyst-mcp sidecar)
 * can create chat sessions, dispatch prompts, and read transcripts
 * without driving the UI.
 *
 * 2026-05-18: born tonight to replace the "user manually clicks +,
 * switches model dropdown, pastes prompt" loop. Five paths were
 * evaluated (renderer HTTP bridge, main-process HTTP, SQLite injection,
 * file-watch, MCP sidecar). Pantheon council + Trident consensus picked
 * main-process HTTP as the primary control plane; the MCP sidecar
 * (phase 2) wraps this API in standard MCP tool shape.
 *
 * Security model:
 *   - Reuses the per-launch mcpAuthToken (random 32-byte hex). The
 *     same token gates /mcp, so external callers and SDK subprocesses
 *     authenticate identically.
 *   - Token is exported to disk at userData/.control-token with mode
 *     0o600 so sidecars and scripts can read it. Token rotates per
 *     launch — never persisted across runs in any persistent form.
 *   - Port is exported to userData/.control-port for sidecars that
 *     need to discover the actual port (the MCP server falls forward
 *     when 3456 is taken).
 *   - Host header is validated to localhost variants to defeat DNS
 *     rebinding (per CVE-2025-49596: MCP Inspector RCE).
 *   - Bind is enforced 127.0.0.1 by httpServer.ts at the listen call.
 *
 * Contract is versioned: /control/v1/*. When the IPC contract or the
 * orchestration semantics shift in a way that breaks external callers,
 * bump to /control/v2/* without removing v1 for the migration window.
 */

import { IncomingMessage, ServerResponse } from "http";
import * as fs from "fs";
import * as path from "path";
import { app, BrowserWindow, webContents } from "electron";
import {
  AISessionsRepository,
  AgentMessagesRepository,
} from "@nimbalyst/runtime";
import { requireMcpAuth, getMcpAuthToken } from "./mcpAuth";
import { windowStates } from "../window/windowState";

const VALID_HOSTS = new Set([
  "localhost",
  "127.0.0.1",
]);

/**
 * Write the per-launch token + actual listening port to userData so
 * external automation can discover them. Called once from index.ts
 * after startMcpHttpServer resolves. The token already exists in
 * memory (generated by generateMcpAuthToken); we only persist the
 * pair so a sidecar can hand-shake without a separate exchange.
 *
 * Files are mode 0o600 (user read/write only). On Windows the
 * effective ACL is the file owner only — node's fs.chmodSync maps
 * mode bits to the closest Windows equivalent.
 */
export function writeControlPlaneDiscoveryFiles(actualPort: number): void {
  const token = getMcpAuthToken();
  if (!token) {
    console.warn("[control] cannot write discovery files: token not generated");
    return;
  }
  const dir = app.getPath("userData");
  const tokenPath = path.join(dir, ".control-token");
  const portPath = path.join(dir, ".control-port");
  try {
    fs.writeFileSync(tokenPath, token, { mode: 0o600 });
    fs.writeFileSync(portPath, String(actualPort), { mode: 0o600 });
    console.log(
      `[control] wrote discovery files: ${tokenPath} / ${portPath} (port=${actualPort})`
    );
  } catch (err) {
    console.error("[control] failed to write discovery files:", err);
  }
}

/**
 * Validate the Host header is a localhost variant. Defends against
 * DNS rebinding attacks where an attacker's page resolves a hostname
 * they control to 127.0.0.1 and POSTs to localhost — bypassing CORS.
 * Per CVE-2025-49596 this is a live exploit class as of 2025.
 */
function isLocalhostHost(req: IncomingMessage): boolean {
  const raw = req.headers["host"];
  if (typeof raw !== "string") return false;
  const hostOnly = raw.split(":")[0].toLowerCase();
  return VALID_HOSTS.has(hostOnly);
}

function jsonResponse(res: ServerResponse, status: number, body: unknown): void {
  const payload = JSON.stringify(body);
  res.writeHead(status, {
    "Content-Type": "application/json",
    "Content-Length": Buffer.byteLength(payload),
  });
  res.end(payload);
}

async function readJsonBody(req: IncomingMessage, maxBytes = 256 * 1024): Promise<unknown> {
  return new Promise((resolve, reject) => {
    let total = 0;
    const chunks: Buffer[] = [];
    req.on("data", (chunk: Buffer) => {
      total += chunk.length;
      if (total > maxBytes) {
        reject(new Error(`request body exceeds ${maxBytes} bytes`));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => {
      try {
        const raw = Buffer.concat(chunks).toString("utf8");
        if (!raw) {
          resolve({});
          return;
        }
        resolve(JSON.parse(raw));
      } catch (err) {
        reject(err);
      }
    });
    req.on("error", reject);
  });
}

/**
 * Find a renderer that owns a given workspace, so we can broadcast
 * UI-refresh signals after writing into the session DB. Returns
 * undefined if no matching window is open — that's not an error:
 * the session row exists, the renderer will pick it up next time
 * the user opens that workspace, or polling will catch it.
 *
 * Implementation note: we intentionally don't require the renderer
 * to be open. The control plane's contract is "session persisted +
 * dispatch queued"; UI refresh is best-effort.
 */
function notifyRenderer(channel: string, payload: unknown): void {
  try {
    for (const wc of webContents.getAllWebContents()) {
      if (!wc.isDestroyed()) {
        wc.send(channel, payload);
      }
    }
  } catch (err) {
    console.warn(`[control] notifyRenderer(${channel}) failed:`, err);
  }
}

/**
 * Heavy-hammer refresh: force a full webContents.reload() on every
 * window currently pointing at the given workspace. Used as the v1
 * fallback before the renderer learns to handle the lightweight
 * sessions:invalidate IPC; losing transcript scroll / composer text
 * is the trade for guaranteed visibility of externally-created
 * sessions. Once the invalidate listener ships, callers should stop
 * passing ?refresh=reload and this path becomes opt-in for the
 * rare "renderer state is hopelessly stale, just nuke it" case.
 */
function reloadWindowsForWorkspace(workspaceId: string): void {
  try {
    let count = 0;
    for (const [, state] of windowStates) {
      if (!state) continue;
      const owns =
        state.workspacePath === workspaceId ||
        state.activeWorkspacePath === workspaceId ||
        state.additionalWorkspacePaths?.includes(workspaceId);
      if (!owns) continue;
      const win = state as unknown as { window?: BrowserWindow };
      // windowStates values may not carry the BrowserWindow directly; fall
      // back to enumerating all windows and matching by webContents URL is
      // unreliable. Simplest: reload all windows since the workspace match
      // already filtered the set, and the typical user has one window per
      // workspace.
      for (const w of BrowserWindow.getAllWindows()) {
        if (!w.isDestroyed()) {
          w.webContents.reload();
          count++;
        }
      }
      break; // one reload pass covers all workspaces simultaneously
    }
    console.log(`[control] reloaded ${count} window(s) for workspace ${workspaceId}`);
  } catch (err) {
    console.warn("[control] reloadWindowsForWorkspace failed:", err);
  }
}

// -------------------------------------------------------------------- //
// Routes
// -------------------------------------------------------------------- //

interface CreateSessionBody {
  workspaceId: string;
  provider?: string;
  model?: string;
  title?: string;
  agentRole?: string;
  // 2026-05-18: per-session wall-clock timeout for KCS swarm dispatch.
  // Stored in session metadata; KimiClawProvider reads at dispatch time
  // to override its 1800s default. Useful for 8-agent DealMatrix-class
  // prompts that need 2400-3600s. Ignored by non-KCS providers.
  timeoutS?: number;
}

async function handleCreateSession(req: IncomingMessage, res: ServerResponse): Promise<void> {
  let body: CreateSessionBody;
  try {
    body = (await readJsonBody(req)) as CreateSessionBody;
  } catch (err) {
    jsonResponse(res, 400, { error: "invalid_body", detail: String(err) });
    return;
  }
  if (!body.workspaceId) {
    jsonResponse(res, 400, { error: "missing_field", field: "workspaceId" });
    return;
  }
  const provider = (body.provider || "kimiclaw").trim();
  const model = body.model || "kimi-code/kimi-for-coding";
  const title = body.title || "Untitled (control-plane)";
  const agentRole = body.agentRole || "standard";

  // Mirror the id-generation pattern from the renderer (sessions:create
  // expects the caller to supply the id). Random 16 hex chars.
  const sessionId =
    "ctrl_" +
    Array.from({ length: 16 }, () =>
      Math.floor(Math.random() * 16).toString(16)
    ).join("");

  try {
    await AISessionsRepository.create({
      id: sessionId,
      provider: provider as any,
      model,
      title,
      workspaceId: body.workspaceId,
      providerConfig: undefined,
      providerSessionId: undefined,
      worktreeId: null,
      agentRole: agentRole as any,
      createdBySessionId: null,
    });
    // Stash per-session overrides in metadata. The KimiClawProvider
    // reads .metadata.timeoutS at dispatch time (see KimiClawProvider.ts
    // sessionTimeoutOverride lookup). Skipped when no overrides supplied
    // to avoid an unnecessary write.
    if (typeof body.timeoutS === "number" && body.timeoutS > 0) {
      await AISessionsRepository.updateMetadata(sessionId, {
        metadata: { timeoutS: body.timeoutS },
      });
    }
    // Two refresh strategies fire here:
    //  (a) sessions:invalidate IPC — the proper, lightweight path.
    //      The renderer (when patched in step 2) listens for this and
    //      calls aiGetSessions() to refresh the Jotai store WITHOUT
    //      reloading the page (preserves transcript scroll position,
    //      composer text, expanded panes).
    //  (b) reload-on-owning-window fallback — heavy hammer used when
    //      the renderer hasn't been patched yet OR ?refresh=reload is
    //      passed on the request. Forces a full webContents.reload()
    //      of windows that own the target workspace, which guarantees
    //      ai:getSessions runs fresh. Loses UI state.
    notifyRenderer("sessions:invalidate", {
      reason: "external-create",
      sessionId,
      workspaceId: body.workspaceId,
    });
    // 2026-05-18 (post-step-2-validated): default is invalidate-only
    // because App.tsx's sessions:invalidate listener confirmed working
    // — externally-created sessions appear in the sidebar within ~200ms
    // without disturbing UI state. Opt in to ?refresh=reload only for
    // the rare "renderer state is hopelessly stale, nuke it" case.
    const url = new URL(req.url || "/", "http://localhost");
    const mode = url.searchParams.get("refresh") || "invalidate-only";
    if (mode === "reload") {
      reloadWindowsForWorkspace(body.workspaceId);
    }
    jsonResponse(res, 201, {
      session_id: sessionId,
      provider,
      model,
      title,
      workspace_id: body.workspaceId,
    });
  } catch (err) {
    console.error("[control] create session failed:", err);
    jsonResponse(res, 500, { error: "create_failed", detail: String(err) });
  }
}

interface SendMessageBody {
  prompt: string;
  // Optional: caller can pre-classify the input. Defaults to "user".
  source?: "user" | "agent" | "system";
}

async function handleSendMessage(
  req: IncomingMessage,
  res: ServerResponse,
  sessionId: string
): Promise<void> {
  let body: SendMessageBody;
  try {
    body = (await readJsonBody(req)) as SendMessageBody;
  } catch (err) {
    jsonResponse(res, 400, { error: "invalid_body", detail: String(err) });
    return;
  }
  if (!body.prompt || typeof body.prompt !== "string") {
    jsonResponse(res, 400, { error: "missing_field", field: "prompt" });
    return;
  }
  const session = await AISessionsRepository.get(sessionId);
  if (!session) {
    jsonResponse(res, 404, { error: "session_not_found", session_id: sessionId });
    return;
  }

  // 2026-05-18 (post-v3-validated): default is "canonical" because the
  // queued path only drains when the session is OPEN in a chat tab.
  // External automation (nimbalyst-mcp, regression tests, this control
  // plane in general) virtually never wants that — the whole point is
  // headless dispatch. Opt in to ?dispatch=queued only when you're
  // injecting from inside the renderer's lifecycle (rare).
  const url = new URL(req.url || "/", "http://localhost");
  const dispatchMode = url.searchParams.get("dispatch") || "canonical";

  if (dispatchMode === "canonical") {
    // v3 path: invoke the canonical streamingHandler that the renderer's
    // ai:sendMessage IPC uses. The provider dispatches IMMEDIATELY and
    // writes results to ai_agent_messages — no renderer involvement
    // needed. Fire-and-forget from the HTTP layer; poll the transcript
    // route to read responses as they land.
    try {
      const indexModule = await import("../index");
      const ai = indexModule.getAIServiceForControlPlane();
      if (!ai) {
        jsonResponse(res, 503, { error: "ai_service_unavailable", detail: "AIService not yet constructed" });
        return;
      }
      const workspacePath = (session as { workspacePath?: string }).workspacePath;
      if (!workspacePath) {
        jsonResponse(res, 500, { error: "session_missing_workspace", session_id: sessionId });
        return;
      }
      // Fire-and-forget. The HTTP caller gets 202 immediately; the
      // dispatch runs in the background. Errors are logged but don't
      // surface to the HTTP caller (they're in the persisted transcript
      // as an error message row, retrievable via the transcript route).
      ai.dispatchExternal(body.prompt, sessionId, workspacePath).catch((err) => {
        console.error(`[control] canonical dispatch failed for ${sessionId}:`, err);
      });
      jsonResponse(res, 202, {
        accepted: true,
        session_id: sessionId,
        dispatch_mode: "canonical",
        note: "Provider invoked; poll /sessions/:id/transcript for results.",
      });
    } catch (err) {
      console.error("[control] canonical dispatch setup failed:", err);
      jsonResponse(res, 500, { error: "dispatch_failed", detail: String(err) });
    }
    return;
  }

  // Default: queued-prompts path. Mirrors `ai:createQueuedPrompt`
  // (AIService.ts:1958) — the same path the renderer takes for
  // fire-and-forget injection. The session must be OPEN in a chat
  // tab for the dispatch loop to drain the queue. Use ?dispatch=canonical
  // to force dispatch without renderer involvement.
  try {
    const { getQueuedPromptsStore } = await import("../services/RepositoryManager");
    const queueStore = getQueuedPromptsStore();
    const promptId = `ctrl-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
    await queueStore.create({
      id: promptId,
      sessionId,
      prompt: body.prompt,
      attachments: undefined,
      documentContext: undefined,
    });
    notifyRenderer("ai:queuedPromptsReceived", {
      sessionId,
      promptCount: 1,
    });
    jsonResponse(res, 202, {
      accepted: true,
      session_id: sessionId,
      prompt_id: promptId,
      dispatch_mode: "queued",
    });
  } catch (err) {
    console.error("[control] send message failed:", err);
    jsonResponse(res, 500, { error: "send_failed", detail: String(err) });
  }
}

async function handleGetSession(
  res: ServerResponse,
  sessionId: string
): Promise<void> {
  const session = await AISessionsRepository.get(sessionId);
  if (!session) {
    jsonResponse(res, 404, { error: "session_not_found", session_id: sessionId });
    return;
  }
  jsonResponse(res, 200, session);
}

/**
 * List sessions. Two query modes:
 *   - ?workspace_id=X  → sessions in that workspace (uses repository's
 *     native list which is indexed for this)
 *   - no workspace_id  → enumerate sessions across all workspaces by
 *     scanning windowed BrowserWindow states, then listing each
 *     workspace's sessions. Useful for external automation to
 *     discover what workspaces exist without prior knowledge.
 *
 * Returns minimal SessionMeta (id, provider, model, title, workspaceId,
 * updatedAt) so callers can choose which one to dispatch into.
 */
async function handleListSessions(
  req: IncomingMessage,
  res: ServerResponse
): Promise<void> {
  const url = new URL(req.url || "/", "http://localhost");
  const workspaceId = url.searchParams.get("workspace_id");
  const limit = Math.min(
    Math.max(parseInt(url.searchParams.get("limit") || "50", 10), 1),
    500
  );

  if (workspaceId) {
    try {
      const sessions = await AISessionsRepository.list(workspaceId, { limit });
      jsonResponse(res, 200, {
        workspace_id: workspaceId,
        session_count: sessions.length,
        sessions,
      });
    } catch (err) {
      console.error("[control] list workspace sessions failed:", err);
      jsonResponse(res, 500, { error: "list_failed", detail: String(err) });
    }
    return;
  }

  // No workspace_id supplied — discover the workspaces nimbalyst's open
  // windows are pointing at and list sessions from each. Workspaces are
  // tracked as filesystem PATHS in windowStates (see windowState.ts:14
  // resolveActiveWorkspacePath). Each window has a primary workspacePath
  // and may carry additionalWorkspacePaths in the project rail; both
  // count as "interest" so we include them.
  const seenWorkspaces = new Set<string>();
  try {
    for (const [, state] of windowStates) {
      if (!state) continue;
      if (state.workspacePath) seenWorkspaces.add(state.workspacePath);
      if (state.activeWorkspacePath) seenWorkspaces.add(state.activeWorkspacePath);
      const extras = state.additionalWorkspacePaths;
      if (Array.isArray(extras)) {
        for (const p of extras) {
          if (p) seenWorkspaces.add(p);
        }
      }
    }
  } catch (err) {
    console.warn("[control] could not enumerate window workspaces:", err);
  }

  const out: Array<Record<string, unknown>> = [];
  for (const wid of seenWorkspaces) {
    try {
      const sessions = await AISessionsRepository.list(wid, { limit });
      for (const s of sessions) {
        out.push({ ...s, workspaceId: wid });
      }
    } catch (err) {
      console.warn(`[control] list failed for workspace ${wid}:`, err);
    }
  }

  jsonResponse(res, 200, {
    workspace_count: seenWorkspaces.size,
    workspace_ids: Array.from(seenWorkspaces),
    session_count: out.length,
    sessions: out,
  });
}

async function handleGetTranscript(
  req: IncomingMessage,
  res: ServerResponse,
  sessionId: string
): Promise<void> {
  const session = await AISessionsRepository.get(sessionId);
  if (!session) {
    jsonResponse(res, 404, { error: "session_not_found", session_id: sessionId });
    return;
  }
  const url = new URL(req.url || "/", "http://localhost");
  const limit = Math.min(
    Math.max(parseInt(url.searchParams.get("limit") || "200", 10), 1),
    1000
  );
  const offset = Math.max(parseInt(url.searchParams.get("offset") || "0", 10), 0);
  const includeHidden = url.searchParams.get("include_hidden") === "1";
  try {
    const messages = await AgentMessagesRepository.list(sessionId, {
      limit,
      offset,
      includeHidden,
    });
    jsonResponse(res, 200, {
      session_id: sessionId,
      message_count: messages.length,
      limit,
      offset,
      include_hidden: includeHidden,
      messages,
    });
  } catch (err) {
    console.error("[control] get transcript failed:", err);
    jsonResponse(res, 500, { error: "transcript_failed", detail: String(err) });
  }
}

async function handleHealth(res: ServerResponse): Promise<void> {
  // Renderer-readiness probe. If at least one open BrowserWindow has
  // finished loading, we report ready=true. Sessions can be CREATED
  // without a renderer (the row is in PGLite either way), but dispatch
  // is only meaningful when a renderer can pick up the queued prompt
  // and run the provider.
  let rendererReady = false;
  try {
    for (const win of BrowserWindow.getAllWindows()) {
      if (!win.isDestroyed() && !win.webContents.isLoading()) {
        rendererReady = true;
        break;
      }
    }
  } catch {
    // Defensive: if BrowserWindow query fails, report not-ready
    // rather than misleading the caller.
  }
  jsonResponse(res, 200, {
    ok: true,
    renderer_ready: rendererReady,
    pid: process.pid,
    version: "control-plane-v1-2026-05-18",
  });
}

// -------------------------------------------------------------------- //
// Dispatcher — invoked from httpServer.ts when pathname starts with
// /control/v1. Returns true if the request was handled (response sent),
// false if the dispatcher didn't recognise the route (httpServer.ts
// then falls through to its existing 404 path).
// -------------------------------------------------------------------- //

const CONTROL_PREFIX = "/control/v1";

export async function handleControlRequest(
  req: IncomingMessage,
  res: ServerResponse,
  pathname: string
): Promise<boolean> {
  if (!pathname.startsWith(CONTROL_PREFIX)) {
    return false;
  }
  // Defence in depth: Host header validation BEFORE auth check.
  // Even with a valid token, a request from an attacker page using
  // DNS rebinding must not reach the route handlers.
  if (!isLocalhostHost(req)) {
    jsonResponse(res, 403, { error: "forbidden_host" });
    return true;
  }
  if (!requireMcpAuth(req)) {
    jsonResponse(res, 401, { error: "unauthorized" });
    return true;
  }

  const subpath = pathname.slice(CONTROL_PREFIX.length); // e.g. "/sessions/abc/messages"
  const method = req.method || "GET";

  // GET /control/v1/health
  if (subpath === "/health" && method === "GET") {
    await handleHealth(res);
    return true;
  }

  // GET /control/v1/sessions  (optionally ?workspace_id=X)
  if (subpath === "/sessions" && method === "GET") {
    await handleListSessions(req, res);
    return true;
  }

  // POST /control/v1/sessions
  if (subpath === "/sessions" && method === "POST") {
    await handleCreateSession(req, res);
    return true;
  }

  // /control/v1/sessions/:id ...
  const sessionMatch = subpath.match(/^\/sessions\/([a-zA-Z0-9_\-]+)(\/.*)?$/);
  if (sessionMatch) {
    const sessionId = sessionMatch[1];
    const tail = sessionMatch[2] || "";

    if (tail === "" && method === "GET") {
      await handleGetSession(res, sessionId);
      return true;
    }
    if (tail === "/messages" && method === "POST") {
      await handleSendMessage(req, res, sessionId);
      return true;
    }
    if (tail === "/transcript" && method === "GET") {
      await handleGetTranscript(req, res, sessionId);
      return true;
    }
  }

  jsonResponse(res, 404, { error: "route_not_found", path: pathname, method });
  return true;
}
